In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("StudentsPerformance.csv")

In [6]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [10]:
df.shape

(1000, 8)

In [11]:
df.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

In [4]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [12]:
df.fillna(df.mean(numeric_only=True), inplace=True)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [13]:
df[(df['math score'] > 100) | (df['math score'] < 0)]

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

In [15]:
df['math score'] = df['math score'].astype(float)

In [16]:
df.loc[(df['math score'] > 100) | (df['math score'] < 0), 'math score'] = df['math score'].mean()

In [17]:
Q1 = df['math score'].quantile(0.25)
Q3 = df['math score'].quantile(0.75)
IQR = Q3 - Q1

In [18]:
outliers = df[(df['math score'] < (Q1 - 1.5 * IQR)) | (df['math score'] > (Q3 + 1.5 * IQR))]

In [19]:
df['math score'] = df['math score'].clip(Q1, Q3)

In [20]:
import numpy as np

df['math_log'] = np.log(df['math score'])

In [21]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,math_log
0,female,group B,bachelor's degree,standard,none,72.0,72,74,4.276666
1,female,group C,some college,standard,completed,69.0,90,88,4.234107
2,female,group B,master's degree,standard,none,77.0,95,93,4.343805
3,male,group A,associate's degree,free/reduced,none,57.0,57,44,4.043051
4,male,group C,some college,standard,none,76.0,78,75,4.330733