In [18]:
import pandas as pd

In [19]:
df = pd.read_csv('BostonHousing.csv')

In [20]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [21]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [22]:
#import data
x = df.drop('medv', axis = 1)

#output data
y = df['medv']

In [23]:
x.shape

(506, 13)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state = 0, test_size = 0.25)

In [26]:
x_train

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
245,0.19133,22.0,5.86,0,0.431,5.605,70.2,7.9549,7,330,19.1,389.13,18.46
59,0.10328,25.0,5.13,0,0.453,5.927,47.2,6.9320,8,284,19.7,396.90,9.22
276,0.10469,40.0,6.41,1,0.447,7.267,49.0,4.7872,4,254,17.6,389.25,6.05
395,8.71675,0.0,18.10,0,0.693,6.471,98.8,1.7257,24,666,20.2,391.98,17.12
416,10.83420,0.0,18.10,0,0.679,6.782,90.8,1.8195,24,666,20.2,21.57,25.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,0.28392,0.0,7.38,0,0.493,5.708,74.3,4.7211,5,287,19.6,391.13,11.74
192,0.08664,45.0,3.44,0,0.437,7.178,26.3,6.4798,5,398,15.2,390.49,2.87
117,0.15098,0.0,10.01,0,0.547,6.021,82.6,2.7474,6,432,17.8,394.51,10.30
47,0.22927,0.0,6.91,0,0.448,6.030,85.5,5.6894,3,233,17.9,392.74,18.80
172,0.13914,0.0,4.05,0,0.510,5.572,88.5,2.5961,5,296,16.6,396.90,14.69

In [27]:
x_train.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
245,0.19133,22.0,5.86,0,0.431,5.605,70.2,7.9549,7,330,19.1,389.13,18.46
59,0.10328,25.0,5.13,0,0.453,5.927,47.2,6.9320,8,284,19.7,396.90,9.22
276,0.10469,40.0,6.41,1,0.447,7.267,49.0,4.7872,4,254,17.6,389.25,6.05
395,8.71675,0.0,18.10,0,0.693,6.471,98.8,1.7257,24,666,20.2,391.98,17.12
416,10.83420,0.0,18.10,0,0.679,6.782,90.8,1.8195,24,666,20.2,21.57,25.79

In [28]:
x_train.shape

(379, 13)

In [29]:
x_test.shape

(127, 13)

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
regressor = LinearRegression()

In [32]:
regressor.fit(x_train, y_train)

LinearRegression()

In [33]:
regressor.coef_

array([-1.17735289e-01,  4.40174969e-02, -5.76814314e-03,  2.39341594e+00,
       -1.55894211e+01,  3.76896770e+00, -7.03517828e-03, -1.43495641e+00,
        2.40081086e-01, -1.12972810e-02, -9.85546732e-01,  8.44443453e-03,
       -4.99116797e-01])

In [34]:
regressor.intercept_

np.float64(36.93325545711923)

In [35]:
#predictions
y_pred = regressor.predict(x_test)

In [36]:
y_pred.shape

(127,)

In [37]:
result = pd.DataFrame({'Actual':y_test, 'Producted':y_pred})

In [38]:
result

     Actual  Producted
329    22.6  24.952333
371    50.0  23.616997
219    23.0  29.205886
403     8.3  11.960705
78     21.2  21.333620
..      ...        ...
49     19.4  17.538048
498    21.2  21.502223
309    20.3  23.632813
124    18.8  20.282598
306    33.4  35.179734

[127 rows x 2 columns]

In [41]:
residual_error = abs(y_test-y_pred)

In [42]:
residual_error

329     2.352333
371    26.383003
219     6.205886
403     3.660705
78      0.133620
         ...
49      1.861952
498     0.302223
309     3.332813
124     1.482598
306     1.779734
Name: medv, Length: 127, dtype: float64

In [43]:
residual_error;

In [44]:
#mean absolute error
sum(residual_error)/len(residual_error)

3.66833014813572

In [46]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_pred,y_test)

3.668330148135719

In [49]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_pred)

0.1754993780061571

In [50]:
regressor.score(x_test,y_test)

0.6354638433202128

In [51]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6354638433202128